db:
  host: '172.17.71.107'
  port: '20002'
  user: 'simon'
  pass: 'simonsimon'
  name: 'msgr_db'
server:
  host: '127.0.0.1:8081'
  secretKey: "test"
debug:
  switch: 'off'
  login: 'on'
  cors: 'on'